BEGIN TRANSACTION;
DROP TABLE IF EXISTS `todo`;
CREATE TABLE IF NOT EXISTS `todo` (
	`text`	STRING NOT NULL,
	`created`	DATETIME NOT NULL,
	`deleted`	INTEGER NOT NULL DEFAULT 0,
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`done`	INTEGER NOT NULL DEFAULT 0
);
COMMIT;
